version: "3.8"

services:
  repo-update:
    container_name: update-service
    image: alpine
    volumes:
      - .:/repo
    working_dir: /repo
    entrypoint: ["sh", "-c", "chmod +x update-repo.sh && ./update-repo.sh"]

  laravel-backend:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    container_name: laravel-backend
    volumes:
      - ./laravel-backend:/var/www/html
    ports:
      - "2402:80"
    depends_on:
      - rob18n-db
      - repo-update
    entrypoint: >
      sh -c "
      cd /var/www/html &&
      composer install &&
      cp .env.example .env &&
      php artisan key:generate &&
      php artisan migrate --force &&
      php-fpm -D &&
      nginx -g 'daemon off;'
      "

  vue-frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "3112:80"
    depends_on:
      - repo-update

  rob18n-db:
    image: mysql:8.0
    container_name: rob18n-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "2506:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
